### ISSUE TITLE
Research Spotlights page

### ISSUE THREAD

**Issue by sdmcraft** [adobe/dx-portal#11]
[Refer this document.](https://adobe.sharepoint.com/:w:/r/sites/DXIndia/_layouts/15/Doc.aspx?sourcedoc=%7BCBC30720-62F9-40CB-9BB6-7ADF15447F91%7D&file=Research%20Spotlights.docx&action=default&mobileredirect=true)

**Comment by sdmcraft** [comment]
Work in progress url : https://main--dx-portal--adobe.hlx.page/researchers/research-spotlights

**Comment by RitwikSrivastava** [comment]
https://main--dx-portal--adobe.hlx.live/researchers/research-spotlights
implemented 3 articles on the main page with a link to other page which contains some other articles.
