### ISSUE TITLE
DevX Code Registration Form

### ISSUE THREAD

**Issue by RitwikSrivastava** [adobe/dx-portal#3]

**Comment by sdmcraft** [comment]
As discussed, the forms need to be made event specific and have meaningful filenames.

**Comment by RitwikSrivastava** [comment]
Done. made devxcode form inside developers folder and provided a more meaningful name.

**Comment by RitwikSrivastava** [comment]
https://main--dx-portal--srshrm.hlx.page/developers/devxcodeform.json
