### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by hparwani2** [adobe/dx-portal#5]
#### Steps to Reproduce
ON pressing Enter after the search query, it takes us to helpx.adobe.com page
the pages shown in search page have title in lower case. ex: devx

**Comment by sdmcraft** [comment]
Enter button press takes to helpx.adobe.com

**Comment by hparwani2** [comment]
PR raised on milo to modify gnav to remove enter event
https://github.com/adobecom/milo/pull/1098

**Comment by sdmcraft** [comment]
Closing this out for lack of activity and with the assumption that opening helpx on pressing "Enter" key is acceptable.
