### ISSUE TITLE
Improve LHS

### ISSUE THREAD

**Issue by sdmcraft** [adobe/dx-portal#6]
![image](https://github.com/adobe/dx-portal/assets/1191451/7e8ababa-2661-420f-a942-5471ed73fb7b)

Report: https://pagespeed.web.dev/analysis/https-main--dx-portal--adobe-hlx-live/2seiv35y03?form_factor=mobile

**Comment by hparwani2** [comment]
https://main--dx-portal--adobe.hlx.live/?martech=off

martech=off parameter disables Adobe target script, hence performance improves.
